### PR TITLE
Merged pull requests

### PR DESCRIPTION
**Pull request by heuer**
This pull request solves merging conflicts and represents the result of applying pull requests
#9, #10, #11, #14, #16, #19, #21

### CODE REVIEW

**Comment by heuer** [comment]
Merged pull request #25

**Comment by mnooner256** [comment]
I don't like having a local copy of pypng. It would be really difficult to keep the local version up to date with the official version.

**Comment by mnooner256** [comment]
Can you tell me why you used only those encodings? If using binary mode, then it should be able to take basically any encoding.

**Comment by heuer** [comment]
Local PyPNG: ACK, although it falls back to a newer version if a user has installed a newer version. Anyway, don't add it if you don't like it.

Encodings: You're right. But I thought that these encodings are common (and supported by decoders) enough to limit them without adding an ECI header. Acc. to the standard an ECI header is required if encoding != ISO/IEC 8859-1. But the ECI header is not well supported by decoders. Anyway, you may loose this limitation, it makes sense to allow any encoding (and maybe add an ECI header on user's request)

**Comment by mnooner256** [comment]
You are right that ECI should be implemented. I will work on it when I get a chance.

**Comment by mnooner256** [comment]
After three days of working on it. I believe I have merged in all of the major changes you committed. There is some small stuff, but like the encodings I changed or left out.

However, 90% of what your stuff should have made it in. The master repo passes all of the the tests. The only major difference is that the renderers use quiet_zone rather than border.

You submitted a massive amount of stuff (which I certainly appreciate). But it does mean I may have forgotten or missed something. Could you take a quick look and see if there is anything I missed.

**Comment by heuer** [comment]
Sorry for the confusion. Initially I just wanted to make make the SVG output nicer and I missed to create a branch for it.
However, my master branch contains a few improvements like using "tox" for testing against Jython, Py26, Py27 and 3.x.
Unsure if you're interested in the EPS output (also in master).

I just pushed a forgotten commit (a "show" method which I found useful to debug codes). 

You may cherry pick some things from my initial push request #9 which reflects my current state of affairs regarding pyqrcode

**Pull request merged**
